# title: Get matching identifiers for chemicals
# description: Returns all chemicals with their CAS numbers and cross-referenced database identifiers.
# category: Chemicals

SELECT ?CASID ?ChemicalName ?MatchingIDs
WHERE {
  ?CAS a cheminf:000000 ;
    dc:title ?ChemicalName ;
    cheminf:000446 ?CASID ;
    skos:exactMatch ?MatchingIDs .
}
