# title: List identifier-mapped genes for AOPs
# description: Returns all non-annotated genes from Key Events of AOPs, with HGNC symbols and NCBI gene identifiers.
# category: Key Events

SELECT DISTINCT ?aop ?aoptitle ?ketitle ?HGNC ?id
WHERE {
  ?aop a aopo:AdverseOutcomePathway ;
    dc:title ?aoptitle ;
    aopo:has_key_event ?ke .
  ?ke a aopo:KeyEvent ;
    edam:data_1025 ?object ;
    dc:title ?ketitle ;
    rdfs:label ?keid .
  ?object edam:data_2298 ?HGNC ;
    skos:exactMatch ?id .
  ?id a edam:data_1027 ;
    edam:data_1027 ?ncbi .
  # Uncomment the line below to filter for a specific AOP:
  # FILTER (?aop = aop:57)
}
ORDER BY DESC(?aop)
