# title: List Key Events with Ensembl IDs
# description: Returns Key Events and their linked Ensembl gene identifiers through gene/protein annotations.
# category: Key Events

SELECT DISTINCT ?keid ?ketitle ?id ?ensembl
WHERE {
  ?ke a aopo:KeyEvent ;
    edam:data_1025 ?object ;
    dc:title ?ketitle ;
    rdfs:label ?keid .
  ?object skos:exactMatch ?id .
  ?id a edam:data_1033 ;
    edam:data_1033 ?ensembl .
}
