# title: List Key Events with annotated UniProt IDs
# description: Returns Key Events with their annotated protein objects and linked UniProt identifiers, through AOP membership.
# category: Key Events

SELECT DISTINCT ?keid ?ketitle ?objectname ?uniprotID ?uniprot
WHERE {
  ?aop a aopo:AdverseOutcomePathway ;
    rdfs:label ?aop_id ;
    aopo:has_key_event ?ke .
  ?ke pato:0001241 ?object ;
    dc:title ?ketitle ;
    rdfs:label ?keid .
  ?object dc:title ?objectname ;
    skos:exactMatch ?uniprot .
  ?uniprot a edam:data_2291 ;
    edam:data_2291 ?uniprotID .
}
