# title: List methods for AOPs
# description: Returns Key Events with their applicable species and measurement methods for a specific AOP.
# param: aop_id|autocomplete:aop|12|AOP

SELECT DISTINCT ?aop ?ke
  (GROUP_CONCAT(DISTINCT ?speciesname; separator=" | ") AS ?speciesnames)
  ?method
WHERE {
  BIND(aop:{{aop_id}} AS ?aop)
  ?aop aopo:has_key_event ?ke .
  ?ke ncbitaxon:131567 ?taxon .
  ?taxon a ncbitaxon:131567 ;
    dc:title ?speciesname .
  OPTIONAL { ?ke mmo:0000000 ?method . }
}
GROUP BY ?aop ?ke ?method
ORDER BY ASC(?aop)
